#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BotPawn

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BotPawn.BotPawn_C
// 0x0000 (0x06B0 - 0x06B0)
class ABotPawn_C final : public AShooterBot
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BotPawn_C">();
	}
	static class ABotPawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABotPawn_C>();
	}
};
static_assert(alignof(ABotPawn_C) == 0x000010, "Wrong alignment on ABotPawn_C");
static_assert(sizeof(ABotPawn_C) == 0x0006B0, "Wrong size on ABotPawn_C");

}

