#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BotSearchEnemyLOS

#include "Basic.hpp"

#include "BotSearchEnemyLOS_classes.hpp"
#include "BotSearchEnemyLOS_parameters.hpp"


namespace SDK
{

// Function BotSearchEnemyLOS.BotSearchEnemyLOS_C.ExecuteUbergraph_BotSearchEnemyLOS
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBotSearchEnemyLOS_C::ExecuteUbergraph_BotSearchEnemyLOS(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BotSearchEnemyLOS_C", "ExecuteUbergraph_BotSearchEnemyLOS");

	Params::BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BotSearchEnemyLOS.BotSearchEnemyLOS_C.ReceiveTick
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AActor*                           OwnerActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBotSearchEnemyLOS_C::ReceiveTick(class AActor* OwnerActor, float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BotSearchEnemyLOS_C", "ReceiveTick");

	Params::BotSearchEnemyLOS_C_ReceiveTick Parms{};

	Parms.OwnerActor = OwnerActor;
	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

