#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BotSearchEnemyLOS

#include "Basic.hpp"


namespace SDK::Params
{

// Function BotSearchEnemyLOS.BotSearchEnemyLOS_C.ExecuteUbergraph_BotSearchEnemyLOS
// 0x0028 (0x0028 - 0x0000)
struct BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1942[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_OwnerActor;                           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1943[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AShooterAIController*                   K2Node_DynamicCast_AsShooter_AIController;         // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_FindClosestEnemyWithLOS_ReturnValue;      // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS) == 0x000008, "Wrong alignment on BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS");
static_assert(sizeof(BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS) == 0x000028, "Wrong size on BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS");
static_assert(offsetof(BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS, EntryPoint) == 0x000000, "Member 'BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS::EntryPoint' has a wrong offset!");
static_assert(offsetof(BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS, K2Node_Event_OwnerActor) == 0x000008, "Member 'BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS::K2Node_Event_OwnerActor' has a wrong offset!");
static_assert(offsetof(BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS, K2Node_Event_DeltaSeconds) == 0x000010, "Member 'BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS, K2Node_DynamicCast_AsShooter_AIController) == 0x000018, "Member 'BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS::K2Node_DynamicCast_AsShooter_AIController' has a wrong offset!");
static_assert(offsetof(BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS, CallFunc_FindClosestEnemyWithLOS_ReturnValue) == 0x000021, "Member 'BotSearchEnemyLOS_C_ExecuteUbergraph_BotSearchEnemyLOS::CallFunc_FindClosestEnemyWithLOS_ReturnValue' has a wrong offset!");

// Function BotSearchEnemyLOS.BotSearchEnemyLOS_C.ReceiveTick
// 0x0010 (0x0010 - 0x0000)
struct BotSearchEnemyLOS_C_ReceiveTick final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DeltaSeconds;                                      // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BotSearchEnemyLOS_C_ReceiveTick) == 0x000008, "Wrong alignment on BotSearchEnemyLOS_C_ReceiveTick");
static_assert(sizeof(BotSearchEnemyLOS_C_ReceiveTick) == 0x000010, "Wrong size on BotSearchEnemyLOS_C_ReceiveTick");
static_assert(offsetof(BotSearchEnemyLOS_C_ReceiveTick, OwnerActor) == 0x000000, "Member 'BotSearchEnemyLOS_C_ReceiveTick::OwnerActor' has a wrong offset!");
static_assert(offsetof(BotSearchEnemyLOS_C_ReceiveTick, DeltaSeconds) == 0x000008, "Member 'BotSearchEnemyLOS_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

}

