#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BotShootEnemy

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BotShootEnemy.BotShootEnemy_C
// 0x0008 (0x00A0 - 0x0098)
class UBotShootEnemy_C final : public UBTService_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0098(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BotShootEnemy(int32 EntryPoint);
	void ReceiveTick(class AActor* OwnerActor, float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BotShootEnemy_C">();
	}
	static class UBotShootEnemy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBotShootEnemy_C>();
	}
};
static_assert(alignof(UBotShootEnemy_C) == 0x000008, "Wrong alignment on UBotShootEnemy_C");
static_assert(sizeof(UBotShootEnemy_C) == 0x0000A0, "Wrong size on UBotShootEnemy_C");
static_assert(offsetof(UBotShootEnemy_C, UberGraphFrame) == 0x000098, "Member 'UBotShootEnemy_C::UberGraphFrame' has a wrong offset!");

}

