#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BotSearchEnemyLOS

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BotSearchEnemyLOS.BotSearchEnemyLOS_C
// 0x0008 (0x00A0 - 0x0098)
class UBotSearchEnemyLOS_C final : public UBTService_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0098(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BotSearchEnemyLOS(int32 EntryPoint);
	void ReceiveTick(class AActor* OwnerActor, float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BotSearchEnemyLOS_C">();
	}
	static class UBotSearchEnemyLOS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBotSearchEnemyLOS_C>();
	}
};
static_assert(alignof(UBotSearchEnemyLOS_C) == 0x000008, "Wrong alignment on UBotSearchEnemyLOS_C");
static_assert(sizeof(UBotSearchEnemyLOS_C) == 0x0000A0, "Wrong size on UBotSearchEnemyLOS_C");
static_assert(offsetof(UBotSearchEnemyLOS_C, UberGraphFrame) == 0x000098, "Member 'UBotSearchEnemyLOS_C::UberGraphFrame' has a wrong offset!");

}

