#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DmgType_Explosion

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DmgType_Explosion.DmgType_Explosion_C
// 0x0000 (0x0068 - 0x0068)
class UDmgType_Explosion_C final : public UShooterDamageType
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DmgType_Explosion_C">();
	}
	static class UDmgType_Explosion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDmgType_Explosion_C>();
	}
};
static_assert(alignof(UDmgType_Explosion_C) == 0x000008, "Wrong alignment on UDmgType_Explosion_C");
static_assert(sizeof(UDmgType_Explosion_C) == 0x000068, "Wrong size on UDmgType_Explosion_C");

}

