#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HeroTPP_AnimBlueprint

#include "Basic.hpp"

#include "HeroTPP_AnimBlueprint_classes.hpp"
#include "HeroTPP_AnimBlueprint_parameters.hpp"


namespace SDK
{

// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.ExecuteUbergraph_HeroTPP_AnimBlueprint
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHeroTPP_AnimBlueprint_C::ExecuteUbergraph_HeroTPP_AnimBlueprint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeroTPP_AnimBlueprint_C", "ExecuteUbergraph_HeroTPP_AnimBlueprint");

	Params::HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.AnimNotify_Footstep
// (BlueprintCallable, BlueprintEvent)

void UHeroTPP_AnimBlueprint_C::AnimNotify_Footstep()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeroTPP_AnimBlueprint_C", "AnimNotify_Footstep");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.AnimNotify_Jumpland
// (BlueprintCallable, BlueprintEvent)

void UHeroTPP_AnimBlueprint_C::AnimNotify_Jumpland()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeroTPP_AnimBlueprint_C", "AnimNotify_Jumpland");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHeroTPP_AnimBlueprint_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeroTPP_AnimBlueprint_C", "BlueprintUpdateAnimation");

	Params::HeroTPP_AnimBlueprint_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_0C5A88D14987F964D888D88152ACB029
// (BlueprintEvent)

void UHeroTPP_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_0C5A88D14987F964D888D88152ACB029()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeroTPP_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_0C5A88D14987F964D888D88152ACB029");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_D7F0836F46C360751AE6BC95922DEC11
// (BlueprintEvent)

void UHeroTPP_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_D7F0836F46C360751AE6BC95922DEC11()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeroTPP_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_D7F0836F46C360751AE6BC95922DEC11");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_2C883E9C42B867B2498D799B0A738D11
// (BlueprintEvent)

void UHeroTPP_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_2C883E9C42B867B2498D799B0A738D11()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeroTPP_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_2C883E9C42B867B2498D799B0A738D11");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_2321A9F84E5D11B5A25F98953F512310
// (BlueprintEvent)

void UHeroTPP_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_2321A9F84E5D11B5A25F98953F512310()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeroTPP_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HeroTPP_AnimBlueprint_AnimGraphNode_TransitionResult_2321A9F84E5D11B5A25F98953F512310");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UHeroTPP_AnimBlueprint_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeroTPP_AnimBlueprint_C", "AnimGraph");

	Params::HeroTPP_AnimBlueprint_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

