#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HeroTPP_AnimBlueprint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.ExecuteUbergraph_HeroTPP_AnimBlueprint
// 0x03E0 (0x03E0 - 0x0000)
struct HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue; // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1916[0x1];                                     // 0x000B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_1; // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_1;       // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0017(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1917[0x4];                                     // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPawnMovementComponent*                 CallFunc_GetMovementComponent_ReturnValue;         // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AShooterCharacter*                      K2Node_DynamicCast_AsShooter_Character;            // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsRunning_ReturnValue;                    // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1918[0x2];                                     // 0x003A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakVector_X;                            // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1919[0x3];                                     // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_GetAimOffsets_ReturnValue;                // 0x004C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x0064(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_NegateRotator_ReturnValue;                // 0x0074(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_1;          // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetVelocity_ReturnValue;                  // 0x0084(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VSize_ReturnValue;                        // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_Conv_VectorToRotator_ReturnValue;         // 0x0094(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_2;         // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191A[0x3];                                     // 0x00A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_ComposeRotators_ReturnValue;              // 0x00A4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakRotator_Roll_1;                      // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch_1;                     // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw_1;                       // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191B[0x7];                                     // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue_1;            // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_191C[0x4];                                     // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerPawn_C*                          K2Node_DynamicCast_AsPlayer_Pawn;                  // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191D[0x3];                                     // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x00E4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue_2;            // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x00F8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_191E[0x4];                                     // 0x0104(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerPawn_C*                          K2Node_DynamicCast_AsPlayer_Pawn_1;                // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191F[0x7];                                     // 0x0111(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x0120(0x0010)(ConstParm, ReferenceParm)
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue;           // 0x0130(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x0138(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x01C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x01C2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1920[0x1];                                     // 0x01C3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x01C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x01C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x01CC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x01D8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x01E4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x01F0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1921[0x4];                                     // 0x01FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0210(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0228(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x022C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0238(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1922[0x4];                                     // 0x0244(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundCue*                              CallFunc_Map_Find_Value;                           // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1923[0x7];                                     // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue_3;            // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerPawn_C*                          K2Node_DynamicCast_AsPlayer_Pawn_2;                // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1924[0x3];                                     // 0x0269(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x026C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue_1;      // 0x0278(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1925[0x4];                                     // 0x0284(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue_4;            // 0x0288(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerPawn_C*                          K2Node_DynamicCast_AsPlayer_Pawn_3;                // 0x0290(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1926[0x7];                                     // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue_1;              // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array_1;                          // 0x02A8(0x0010)(ConstParm, ReferenceParm)
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue_1;         // 0x02B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit_1;                 // 0x02C0(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue_1;            // 0x0348(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit_1;            // 0x0349(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap_1;         // 0x034A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1927[0x1];                                     // 0x034B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time_1;                    // 0x034C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance_1;                // 0x0350(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location_1;                // 0x0354(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint_1;             // 0x0360(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal_1;                  // 0x036C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal_1;            // 0x0378(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1928[0x4];                                     // 0x0384(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat_1;                 // 0x0388(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor_1;                // 0x0390(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent_1;            // 0x0398(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName_1;             // 0x03A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem_1;                 // 0x03A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex_1;            // 0x03AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex_1;               // 0x03B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart_1;              // 0x03B4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd_1;                // 0x03C0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_2; // 0x03CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundCue*                              CallFunc_Map_Find_Value_1;                         // 0x03D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x03D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_2;       // 0x03D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint) == 0x000008, "Wrong alignment on HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint");
static_assert(sizeof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint) == 0x0003E0, "Wrong size on HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, EntryPoint) == 0x000000, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::EntryPoint' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue) == 0x000004, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000008, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Not_PreBool_ReturnValue) == 0x000009, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Greater_FloatFloat_ReturnValue) == 0x00000A, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_1) == 0x00000C, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BooleanAND_ReturnValue) == 0x000010, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_LessEqual_FloatFloat_ReturnValue_1) == 0x000011, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_LessEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BooleanAND_ReturnValue_1) == 0x000012, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BooleanAND_ReturnValue_2) == 0x000013, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_IsValid_ReturnValue) == 0x000014, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_IsValid_ReturnValue_1) == 0x000015, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_IsValid_ReturnValue_2) == 0x000016, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_IsValid_ReturnValue_3) == 0x000017, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_TryGetPawnOwner_ReturnValue) == 0x000018, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_TryGetPawnOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_Event_DeltaTimeX) == 0x000020, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_Event_DeltaTimeX' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_GetMovementComponent_ReturnValue) == 0x000028, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_GetMovementComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_DynamicCast_AsShooter_Character) == 0x000030, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_DynamicCast_AsShooter_Character' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_IsRunning_ReturnValue) == 0x000039, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_IsRunning_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakVector_X) == 0x00003C, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakVector_Y) == 0x000040, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakVector_Z) == 0x000044, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x000048, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_GetAimOffsets_ReturnValue) == 0x00004C, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_GetAimOffsets_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakRotator_Roll) == 0x000058, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakRotator_Pitch) == 0x00005C, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakRotator_Yaw) == 0x000060, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_K2_GetActorRotation_ReturnValue) == 0x000064, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_K2_GetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000070, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_NegateRotator_ReturnValue) == 0x000074, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_NegateRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Divide_FloatFloat_ReturnValue_1) == 0x000080, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Divide_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_GetVelocity_ReturnValue) == 0x000084, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_GetVelocity_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_VSize_ReturnValue) == 0x000090, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Conv_VectorToRotator_ReturnValue) == 0x000094, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Conv_VectorToRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Greater_FloatFloat_ReturnValue_2) == 0x0000A0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Greater_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_ComposeRotators_ReturnValue) == 0x0000A4, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_ComposeRotators_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakRotator_Roll_1) == 0x0000B0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakRotator_Roll_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakRotator_Pitch_1) == 0x0000B4, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakRotator_Pitch_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakRotator_Yaw_1) == 0x0000B8, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakRotator_Yaw_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x0000BC, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x0000C0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_TryGetPawnOwner_ReturnValue_1) == 0x0000C8, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_TryGetPawnOwner_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Add_FloatFloat_ReturnValue) == 0x0000D0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_DynamicCast_AsPlayer_Pawn) == 0x0000D8, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_DynamicCast_AsPlayer_Pawn' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_DynamicCast_bSuccess_1) == 0x0000E0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0000E4, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_TryGetPawnOwner_ReturnValue_2) == 0x0000F0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_TryGetPawnOwner_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Subtract_VectorVector_ReturnValue) == 0x0000F8, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_DynamicCast_AsPlayer_Pawn_1) == 0x000108, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_DynamicCast_AsPlayer_Pawn_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_DynamicCast_bSuccess_2) == 0x000110, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_GetPlayerPawn_ReturnValue) == 0x000118, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_MakeArray_Array) == 0x000120, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_SpawnSoundAttached_ReturnValue) == 0x000130, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_SpawnSoundAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_LineTraceSingle_OutHit) == 0x000138, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_LineTraceSingle_ReturnValue) == 0x0001C0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_bBlockingHit) == 0x0001C1, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_bInitialOverlap) == 0x0001C2, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_Time) == 0x0001C4, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_Distance) == 0x0001C8, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_Location) == 0x0001CC, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_ImpactPoint) == 0x0001D8, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_Normal) == 0x0001E4, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_ImpactNormal) == 0x0001F0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_PhysMat) == 0x000200, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_HitActor) == 0x000208, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_HitComponent) == 0x000210, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_HitBoneName) == 0x000218, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_HitItem) == 0x000220, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_ElementIndex) == 0x000224, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_FaceIndex) == 0x000228, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_TraceStart) == 0x00022C, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_TraceEnd) == 0x000238, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Map_Find_Value) == 0x000248, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Map_Find_ReturnValue) == 0x000250, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_TryGetPawnOwner_ReturnValue_3) == 0x000258, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_TryGetPawnOwner_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_DynamicCast_AsPlayer_Pawn_2) == 0x000260, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_DynamicCast_AsPlayer_Pawn_2' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_DynamicCast_bSuccess_3) == 0x000268, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x00026C, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Subtract_VectorVector_ReturnValue_1) == 0x000278, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Subtract_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_TryGetPawnOwner_ReturnValue_4) == 0x000288, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_TryGetPawnOwner_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_DynamicCast_AsPlayer_Pawn_3) == 0x000290, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_DynamicCast_AsPlayer_Pawn_3' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_DynamicCast_bSuccess_4) == 0x000298, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_GetPlayerPawn_ReturnValue_1) == 0x0002A0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_GetPlayerPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, K2Node_MakeArray_Array_1) == 0x0002A8, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_SpawnSoundAttached_ReturnValue_1) == 0x0002B8, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_SpawnSoundAttached_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_LineTraceSingle_OutHit_1) == 0x0002C0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_LineTraceSingle_OutHit_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_LineTraceSingle_ReturnValue_1) == 0x000348, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_LineTraceSingle_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_bBlockingHit_1) == 0x000349, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_bBlockingHit_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_bInitialOverlap_1) == 0x00034A, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_bInitialOverlap_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_Time_1) == 0x00034C, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_Time_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_Distance_1) == 0x000350, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_Distance_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_Location_1) == 0x000354, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_Location_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_ImpactPoint_1) == 0x000360, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_ImpactPoint_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_Normal_1) == 0x00036C, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_Normal_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_ImpactNormal_1) == 0x000378, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_ImpactNormal_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_PhysMat_1) == 0x000388, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_PhysMat_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_HitActor_1) == 0x000390, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_HitActor_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_HitComponent_1) == 0x000398, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_HitComponent_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_HitBoneName_1) == 0x0003A0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_HitBoneName_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_HitItem_1) == 0x0003A8, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_HitItem_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_ElementIndex_1) == 0x0003AC, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_ElementIndex_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_FaceIndex_1) == 0x0003B0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_FaceIndex_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_TraceStart_1) == 0x0003B4, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_TraceStart_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_BreakHitResult_TraceEnd_1) == 0x0003C0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_BreakHitResult_TraceEnd_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_2) == 0x0003CC, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Map_Find_Value_1) == 0x0003D0, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_Map_Find_ReturnValue_1) == 0x0003D8, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint, CallFunc_LessEqual_FloatFloat_ReturnValue_2) == 0x0003D9, "Member 'HeroTPP_AnimBlueprint_C_ExecuteUbergraph_HeroTPP_AnimBlueprint::CallFunc_LessEqual_FloatFloat_ReturnValue_2' has a wrong offset!");

// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct HeroTPP_AnimBlueprint_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(HeroTPP_AnimBlueprint_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on HeroTPP_AnimBlueprint_C_BlueprintUpdateAnimation");
static_assert(sizeof(HeroTPP_AnimBlueprint_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on HeroTPP_AnimBlueprint_C_BlueprintUpdateAnimation");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_BlueprintUpdateAnimation, DeltaTimeX) == 0x000000, "Member 'HeroTPP_AnimBlueprint_C_BlueprintUpdateAnimation::DeltaTimeX' has a wrong offset!");

// Function HeroTPP_AnimBlueprint.HeroTPP_AnimBlueprint_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct HeroTPP_AnimBlueprint_C_AnimGraph final
{
public:
	struct FPoseLink                              Param_AnimGraph;                                   // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(HeroTPP_AnimBlueprint_C_AnimGraph) == 0x000008, "Wrong alignment on HeroTPP_AnimBlueprint_C_AnimGraph");
static_assert(sizeof(HeroTPP_AnimBlueprint_C_AnimGraph) == 0x000010, "Wrong size on HeroTPP_AnimBlueprint_C_AnimGraph");
static_assert(offsetof(HeroTPP_AnimBlueprint_C_AnimGraph, Param_AnimGraph) == 0x000000, "Member 'HeroTPP_AnimBlueprint_C_AnimGraph::Param_AnimGraph' has a wrong offset!");

}

