#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HeroFPP_AnimationBlueprint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function HeroFPP_AnimationBlueprint.HeroFPP_AnimationBlueprint_C.ExecuteUbergraph_HeroFPP_AnimationBlueprint
// 0x0390 (0x0390 - 0x0000)
struct HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue; // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_1; // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_1;       // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x000E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_192B[0x1];                                     // 0x000F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_2; // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_2;       // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_192C[0x3];                                     // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_3; // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_3;       // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x001E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x001F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_192D[0x6];                                     // 0x0022(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_192E[0x4];                                     // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPawnMovementComponent*                 CallFunc_GetMovementComponent_ReturnValue;         // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AShooterCharacter*                      K2Node_DynamicCast_AsShooter_Character;            // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsFalling_ReturnValue;                    // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsRunning_ReturnValue;                    // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_192F[0x5];                                     // 0x004B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class AShooterWeapon*                         CallFunc_GetWeapon_ReturnValue;                    // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsTargeting_ReturnValue;                  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1930[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AShooterWeapon_Instant*                 K2Node_DynamicCast_AsShooter_Weapon_Instant;       // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1931[0x3];                                     // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetVelocity_ReturnValue;                  // 0x006C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VSize_ReturnValue;                        // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0082(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0083(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0084(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1932[0x3];                                     // 0x0085(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue_1;            // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerPawn_C*                          K2Node_DynamicCast_AsPlayer_Pawn;                  // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1933[0x3];                                     // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x009C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue_2;            // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x00B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1934[0x4];                                     // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerPawn_C*                          K2Node_DynamicCast_AsPlayer_Pawn_1;                // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1935[0x7];                                     // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue;           // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x00E0(0x0010)(ConstParm, ReferenceParm)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x00F0(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1936[0x7];                                     // 0x0179(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue_3;            // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerPawn_C*                          K2Node_DynamicCast_AsPlayer_Pawn_2;                // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0191(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0192(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1937[0x1];                                     // 0x0193(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x019C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x01A8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x01B4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x01C0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1938[0x4];                                     // 0x01CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x01E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x01F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x01F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x01F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x01FC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0208(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0214(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundCue*                              CallFunc_Map_Find_Value;                           // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1939[0x3];                                     // 0x0229(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue_1;      // 0x022C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue_4;            // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue_1;              // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerPawn_C*                          K2Node_DynamicCast_AsPlayer_Pawn_3;                // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_193A[0x7];                                     // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         K2Node_MakeArray_Array_1;                          // 0x0258(0x0010)(ConstParm, ReferenceParm)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit_1;                 // 0x0268(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue_1;            // 0x02F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit_1;            // 0x02F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap_1;         // 0x02F2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_193B[0x1];                                     // 0x02F3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time_1;                    // 0x02F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance_1;                // 0x02F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location_1;                // 0x02FC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint_1;             // 0x0308(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal_1;                  // 0x0314(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal_1;            // 0x0320(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_193C[0x4];                                     // 0x032C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat_1;                 // 0x0330(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor_1;                // 0x0338(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent_1;            // 0x0340(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName_1;             // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem_1;                 // 0x0350(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex_1;            // 0x0354(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex_1;               // 0x0358(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart_1;              // 0x035C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd_1;                // 0x0368(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_193D[0x4];                                     // 0x0374(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundCue*                              CallFunc_Map_Find_Value_1;                         // 0x0378(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x0380(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_193E[0x7];                                     // 0x0381(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue_1;         // 0x0388(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint) == 0x000008, "Wrong alignment on HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint");
static_assert(sizeof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint) == 0x000390, "Wrong size on HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, EntryPoint) == 0x000000, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::EntryPoint' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue) == 0x000004, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_1) == 0x000008, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x00000C, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_LessEqual_FloatFloat_ReturnValue_1) == 0x00000D, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_LessEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BooleanOR_ReturnValue) == 0x00000E, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_2) == 0x000010, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_LessEqual_FloatFloat_ReturnValue_2) == 0x000014, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_LessEqual_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_3) == 0x000018, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_LessEqual_FloatFloat_ReturnValue_3) == 0x00001C, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_LessEqual_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_IsValid_ReturnValue) == 0x00001D, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BooleanOR_ReturnValue_1) == 0x00001E, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_IsValid_ReturnValue_1) == 0x00001F, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_IsValid_ReturnValue_2) == 0x000020, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_IsValid_ReturnValue_3) == 0x000021, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_TryGetPawnOwner_ReturnValue) == 0x000028, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_TryGetPawnOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_Event_DeltaTimeX) == 0x000030, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_Event_DeltaTimeX' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_GetMovementComponent_ReturnValue) == 0x000038, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_GetMovementComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_AsShooter_Character) == 0x000040, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_AsShooter_Character' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_IsFalling_ReturnValue) == 0x000049, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_IsFalling_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_IsRunning_ReturnValue) == 0x00004A, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_IsRunning_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_GetWeapon_ReturnValue) == 0x000050, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_GetWeapon_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_IsTargeting_ReturnValue) == 0x000058, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_IsTargeting_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_AsShooter_Weapon_Instant) == 0x000060, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_AsShooter_Weapon_Instant' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_bSuccess_1) == 0x000068, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_GetVelocity_ReturnValue) == 0x00006C, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_GetVelocity_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_VSize_ReturnValue) == 0x000078, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_Add_FloatFloat_ReturnValue) == 0x00007C, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000080, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_Not_PreBool_ReturnValue) == 0x000081, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BooleanAND_ReturnValue) == 0x000082, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_Not_PreBool_ReturnValue_1) == 0x000083, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BooleanAND_ReturnValue_1) == 0x000084, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_TryGetPawnOwner_ReturnValue_1) == 0x000088, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_TryGetPawnOwner_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_AsPlayer_Pawn) == 0x000090, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_AsPlayer_Pawn' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_bSuccess_2) == 0x000098, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_K2_GetActorLocation_ReturnValue) == 0x00009C, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_TryGetPawnOwner_ReturnValue_2) == 0x0000A8, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_TryGetPawnOwner_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_Subtract_VectorVector_ReturnValue) == 0x0000B0, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_AsPlayer_Pawn_1) == 0x0000C0, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_AsPlayer_Pawn_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_bSuccess_3) == 0x0000C8, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_GetPlayerPawn_ReturnValue) == 0x0000D0, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_SpawnSoundAttached_ReturnValue) == 0x0000D8, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_SpawnSoundAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_MakeArray_Array) == 0x0000E0, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_LineTraceSingle_OutHit) == 0x0000F0, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_LineTraceSingle_ReturnValue) == 0x000178, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_TryGetPawnOwner_ReturnValue_3) == 0x000180, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_TryGetPawnOwner_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_AsPlayer_Pawn_2) == 0x000188, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_AsPlayer_Pawn_2' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_bSuccess_4) == 0x000190, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_bBlockingHit) == 0x000191, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_bInitialOverlap) == 0x000192, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_Time) == 0x000194, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_Distance) == 0x000198, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_Location) == 0x00019C, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_ImpactPoint) == 0x0001A8, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_Normal) == 0x0001B4, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_ImpactNormal) == 0x0001C0, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_PhysMat) == 0x0001D0, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_HitActor) == 0x0001D8, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_HitComponent) == 0x0001E0, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_HitBoneName) == 0x0001E8, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_HitItem) == 0x0001F0, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_ElementIndex) == 0x0001F4, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_FaceIndex) == 0x0001F8, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_TraceStart) == 0x0001FC, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_TraceEnd) == 0x000208, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000214, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_Map_Find_Value) == 0x000220, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_Map_Find_ReturnValue) == 0x000228, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_Subtract_VectorVector_ReturnValue_1) == 0x00022C, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_Subtract_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_TryGetPawnOwner_ReturnValue_4) == 0x000238, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_TryGetPawnOwner_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_GetPlayerPawn_ReturnValue_1) == 0x000240, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_GetPlayerPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_AsPlayer_Pawn_3) == 0x000248, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_AsPlayer_Pawn_3' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_DynamicCast_bSuccess_5) == 0x000250, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, K2Node_MakeArray_Array_1) == 0x000258, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_LineTraceSingle_OutHit_1) == 0x000268, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_LineTraceSingle_OutHit_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_LineTraceSingle_ReturnValue_1) == 0x0002F0, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_LineTraceSingle_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_bBlockingHit_1) == 0x0002F1, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_bBlockingHit_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_bInitialOverlap_1) == 0x0002F2, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_bInitialOverlap_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_Time_1) == 0x0002F4, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_Time_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_Distance_1) == 0x0002F8, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_Distance_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_Location_1) == 0x0002FC, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_Location_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_ImpactPoint_1) == 0x000308, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_ImpactPoint_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_Normal_1) == 0x000314, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_Normal_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_ImpactNormal_1) == 0x000320, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_ImpactNormal_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_PhysMat_1) == 0x000330, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_PhysMat_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_HitActor_1) == 0x000338, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_HitActor_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_HitComponent_1) == 0x000340, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_HitComponent_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_HitBoneName_1) == 0x000348, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_HitBoneName_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_HitItem_1) == 0x000350, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_HitItem_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_ElementIndex_1) == 0x000354, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_ElementIndex_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_FaceIndex_1) == 0x000358, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_FaceIndex_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_TraceStart_1) == 0x00035C, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_TraceStart_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_BreakHitResult_TraceEnd_1) == 0x000368, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_BreakHitResult_TraceEnd_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_Map_Find_Value_1) == 0x000378, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_Map_Find_ReturnValue_1) == 0x000380, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint, CallFunc_SpawnSoundAttached_ReturnValue_1) == 0x000388, "Member 'HeroFPP_AnimationBlueprint_C_ExecuteUbergraph_HeroFPP_AnimationBlueprint::CallFunc_SpawnSoundAttached_ReturnValue_1' has a wrong offset!");

// Function HeroFPP_AnimationBlueprint.HeroFPP_AnimationBlueprint_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct HeroFPP_AnimationBlueprint_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(HeroFPP_AnimationBlueprint_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on HeroFPP_AnimationBlueprint_C_BlueprintUpdateAnimation");
static_assert(sizeof(HeroFPP_AnimationBlueprint_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on HeroFPP_AnimationBlueprint_C_BlueprintUpdateAnimation");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_BlueprintUpdateAnimation, DeltaTimeX) == 0x000000, "Member 'HeroFPP_AnimationBlueprint_C_BlueprintUpdateAnimation::DeltaTimeX' has a wrong offset!");

// Function HeroFPP_AnimationBlueprint.HeroFPP_AnimationBlueprint_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct HeroFPP_AnimationBlueprint_C_AnimGraph final
{
public:
	struct FPoseLink                              Param_AnimGraph;                                   // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(HeroFPP_AnimationBlueprint_C_AnimGraph) == 0x000008, "Wrong alignment on HeroFPP_AnimationBlueprint_C_AnimGraph");
static_assert(sizeof(HeroFPP_AnimationBlueprint_C_AnimGraph) == 0x000010, "Wrong size on HeroFPP_AnimationBlueprint_C_AnimGraph");
static_assert(offsetof(HeroFPP_AnimationBlueprint_C_AnimGraph, Param_AnimGraph) == 0x000000, "Member 'HeroFPP_AnimationBlueprint_C_AnimGraph::Param_AnimGraph' has a wrong offset!");

}

