#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pickup_Health

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Pickup_Health.Pickup_Health_C
// 0x0000 (0x0268 - 0x0268)
class APickup_Health_C final : public AShooterPickup_Health
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Pickup_Health_C">();
	}
	static class APickup_Health_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APickup_Health_C>();
	}
};
static_assert(alignof(APickup_Health_C) == 0x000008, "Wrong alignment on APickup_Health_C");
static_assert(sizeof(APickup_Health_C) == 0x000268, "Wrong size on APickup_Health_C");

}

