#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProjRocket

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ProjRocket.ProjRocket_C
// 0x0010 (0x0280 - 0x0270)
class AProjRocket_C final : public AShooterProjectile
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        Audio;                                             // 0x0278(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ProjRocket(int32 EntryPoint);
	void OnTakeAnyDamage_Event(class AActor* DamagedActor, float Damage, const class UDamageType* DamageType, class AController* InstigatedBy, class AActor* DamageCauser);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ProjRocket_C">();
	}
	static class AProjRocket_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjRocket_C>();
	}
};
static_assert(alignof(AProjRocket_C) == 0x000008, "Wrong alignment on AProjRocket_C");
static_assert(sizeof(AProjRocket_C) == 0x000280, "Wrong size on AProjRocket_C");
static_assert(offsetof(AProjRocket_C, UberGraphFrame) == 0x000270, "Member 'AProjRocket_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AProjRocket_C, Audio) == 0x000278, "Member 'AProjRocket_C::Audio' has a wrong offset!");

}

