#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProjRocket_Explosion

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ProjRocket_Explosion.ProjRocket_Explosion_C
// 0x0000 (0x02E0 - 0x02E0)
class AProjRocket_Explosion_C final : public AShooterExplosionEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ProjRocket_Explosion_C">();
	}
	static class AProjRocket_Explosion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjRocket_Explosion_C>();
	}
};
static_assert(alignof(AProjRocket_Explosion_C) == 0x000008, "Wrong alignment on AProjRocket_Explosion_C");
static_assert(sizeof(AProjRocket_Explosion_C) == 0x0002E0, "Wrong size on AProjRocket_Explosion_C");

}

