#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sanctuary_Audio

#include "Basic.hpp"

#include "Sanctuary_Audio_classes.hpp"
#include "Sanctuary_Audio_parameters.hpp"


namespace SDK
{

// Function Sanctuary_Audio.Sanctuary_Audio_C.ExecuteUbergraph_Sanctuary_Audio
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASanctuary_Audio_C::ExecuteUbergraph_Sanctuary_Audio(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sanctuary_Audio_C", "ExecuteUbergraph_Sanctuary_Audio");

	Params::Sanctuary_Audio_C_ExecuteUbergraph_Sanctuary_Audio Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Sanctuary_Audio.Sanctuary_Audio_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASanctuary_Audio_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sanctuary_Audio_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Sanctuary_Audio.Sanctuary_Audio_C.SpawnOneShot
// (BlueprintCallable, BlueprintEvent)

void ASanctuary_Audio_C::SpawnOneShot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sanctuary_Audio_C", "SpawnOneShot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Sanctuary_Audio.Sanctuary_Audio_C.PlayOneShots
// (BlueprintCallable, BlueprintEvent)

void ASanctuary_Audio_C::PlayOneShots()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sanctuary_Audio_C", "PlayOneShots");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Sanctuary_Audio.Sanctuary_Audio_C.BndEvt__AudioTrigger_Balcony_02_2_K2Node_ActorBoundEvent_8_ActorEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           OverlappedActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASanctuary_Audio_C::BndEvt__AudioTrigger_Balcony_02_2_K2Node_ActorBoundEvent_8_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sanctuary_Audio_C", "BndEvt__AudioTrigger_Balcony_02_2_K2Node_ActorBoundEvent_8_ActorEndOverlapSignature__DelegateSignature");

	Params::Sanctuary_Audio_C_BndEvt__AudioTrigger_Balcony_02_2_K2Node_ActorBoundEvent_8_ActorEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedActor = OverlappedActor;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Sanctuary_Audio.Sanctuary_Audio_C.BndEvt__AudioTrigger_Balcony_01_K2Node_ActorBoundEvent_7_ActorEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           OverlappedActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASanctuary_Audio_C::BndEvt__AudioTrigger_Balcony_01_K2Node_ActorBoundEvent_7_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sanctuary_Audio_C", "BndEvt__AudioTrigger_Balcony_01_K2Node_ActorBoundEvent_7_ActorEndOverlapSignature__DelegateSignature");

	Params::Sanctuary_Audio_C_BndEvt__AudioTrigger_Balcony_01_K2Node_ActorBoundEvent_7_ActorEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedActor = OverlappedActor;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Sanctuary_Audio.Sanctuary_Audio_C.BndEvt__AudioTrigger_Balcony_02_2_K2Node_ActorBoundEvent_6_ActorBeginOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           OverlappedActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASanctuary_Audio_C::BndEvt__AudioTrigger_Balcony_02_2_K2Node_ActorBoundEvent_6_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sanctuary_Audio_C", "BndEvt__AudioTrigger_Balcony_02_2_K2Node_ActorBoundEvent_6_ActorBeginOverlapSignature__DelegateSignature");

	Params::Sanctuary_Audio_C_BndEvt__AudioTrigger_Balcony_02_2_K2Node_ActorBoundEvent_6_ActorBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedActor = OverlappedActor;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Sanctuary_Audio.Sanctuary_Audio_C.BndEvt__AudioTrigger_Balcony_01_K2Node_ActorBoundEvent_5_ActorBeginOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           OverlappedActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASanctuary_Audio_C::BndEvt__AudioTrigger_Balcony_01_K2Node_ActorBoundEvent_5_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sanctuary_Audio_C", "BndEvt__AudioTrigger_Balcony_01_K2Node_ActorBoundEvent_5_ActorBeginOverlapSignature__DelegateSignature");

	Params::Sanctuary_Audio_C_BndEvt__AudioTrigger_Balcony_01_K2Node_ActorBoundEvent_5_ActorBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedActor = OverlappedActor;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Sanctuary_Audio.Sanctuary_Audio_C.BndEvt__AudioTrigger_Interior_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           OverlappedActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASanctuary_Audio_C::BndEvt__AudioTrigger_Interior_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sanctuary_Audio_C", "BndEvt__AudioTrigger_Interior_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature");

	Params::Sanctuary_Audio_C_BndEvt__AudioTrigger_Interior_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedActor = OverlappedActor;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}

}

