#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sanctuary

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Sanctuary.Sanctuary_C
// 0x0010 (0x0238 - 0x0228)
class ASanctuary_C final : public ALevelScriptActor
{
public:
	TArray<class AActor*>                         Locations;                                         // 0x0228(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Sanctuary_C">();
	}
	static class ASanctuary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASanctuary_C>();
	}
};
static_assert(alignof(ASanctuary_C) == 0x000008, "Wrong alignment on ASanctuary_C");
static_assert(sizeof(ASanctuary_C) == 0x000238, "Wrong size on ASanctuary_C");
static_assert(offsetof(ASanctuary_C, Locations) == 0x000228, "Member 'ASanctuary_C::Locations' has a wrong offset!");

}

