#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TaskAlwaysTrue

#include "Basic.hpp"

#include "TaskAlwaysTrue_classes.hpp"
#include "TaskAlwaysTrue_parameters.hpp"


namespace SDK
{

// Function TaskAlwaysTrue.TaskAlwaysTrue_C.ExecuteUbergraph_TaskAlwaysTrue
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTaskAlwaysTrue_C::ExecuteUbergraph_TaskAlwaysTrue(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TaskAlwaysTrue_C", "ExecuteUbergraph_TaskAlwaysTrue");

	Params::TaskAlwaysTrue_C_ExecuteUbergraph_TaskAlwaysTrue Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TaskAlwaysTrue.TaskAlwaysTrue_C.ReceiveExecute
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AActor*                           OwnerActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTaskAlwaysTrue_C::ReceiveExecute(class AActor* OwnerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TaskAlwaysTrue_C", "ReceiveExecute");

	Params::TaskAlwaysTrue_C_ReceiveExecute Parms{};

	Parms.OwnerActor = OwnerActor;

	UObject::ProcessEvent(Func, &Parms);
}

}

