#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TaskAlwaysTrue

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TaskAlwaysTrue.TaskAlwaysTrue_C
// 0x0008 (0x00B0 - 0x00A8)
class UTaskAlwaysTrue_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_TaskAlwaysTrue(int32 EntryPoint);
	void ReceiveExecute(class AActor* OwnerActor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TaskAlwaysTrue_C">();
	}
	static class UTaskAlwaysTrue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTaskAlwaysTrue_C>();
	}
};
static_assert(alignof(UTaskAlwaysTrue_C) == 0x000008, "Wrong alignment on UTaskAlwaysTrue_C");
static_assert(sizeof(UTaskAlwaysTrue_C) == 0x0000B0, "Wrong size on UTaskAlwaysTrue_C");
static_assert(offsetof(UTaskAlwaysTrue_C, UberGraphFrame) == 0x0000A8, "Member 'UTaskAlwaysTrue_C::UberGraphFrame' has a wrong offset!");

}

