#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeapLauncher_FireCameraShake

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeapLauncher_FireCameraShake.WeapLauncher_FireCameraShake_C
// 0x0000 (0x01B0 - 0x01B0)
class UWeapLauncher_FireCameraShake_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WeapLauncher_FireCameraShake_C">();
	}
	static class UWeapLauncher_FireCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWeapLauncher_FireCameraShake_C>();
	}
};
static_assert(alignof(UWeapLauncher_FireCameraShake_C) == 0x000010, "Wrong alignment on UWeapLauncher_FireCameraShake_C");
static_assert(sizeof(UWeapLauncher_FireCameraShake_C) == 0x0001B0, "Wrong size on UWeapLauncher_FireCameraShake_C");

}

