#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeapGun

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeapGun.WeapGun_C
// 0x0000 (0x04F8 - 0x04F8)
class AWeapGun_C final : public AShooterWeapon_Instant
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WeapGun_C">();
	}
	static class AWeapGun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapGun_C>();
	}
};
static_assert(alignof(AWeapGun_C) == 0x000008, "Wrong alignment on AWeapGun_C");
static_assert(sizeof(AWeapGun_C) == 0x0004F8, "Wrong size on AWeapGun_C");

}

