#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeapLauncher

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeapLauncher.WeapLauncher_C
// 0x0000 (0x04C0 - 0x04C0)
class AWeapLauncher_C final : public AShooterWeapon_Projectile
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WeapLauncher_C">();
	}
	static class AWeapLauncher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapLauncher_C>();
	}
};
static_assert(alignof(AWeapLauncher_C) == 0x000008, "Wrong alignment on AWeapLauncher_C");
static_assert(sizeof(AWeapLauncher_C) == 0x0004C0, "Wrong size on AWeapLauncher_C");

}

